version: '2'
services:
  node1:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "80:80"
  node2:
    environment:
      - PEERS=ws://node1:6001
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "8080:80"
    links:
      - node1:node1
  node3:
    environment:
      - PEERS=ws://node2:6001
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "443:80"
    links:
      - node2:node2
